# Generated by Django 3.2.18 on 2023-05-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0002_auto_20230404_1033'),
        ('favourites', '0005_rename_date_added_favouriteslistitem_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_products', to='products.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_user', to='profiles.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='favouriteslistitem',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='favouriteslistitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='FavouritesList',
        ),
        migrations.DeleteModel(
            name='FavouritesListItem',
        ),
    ]
