# Generated by Django 3.2.18 on 2023-05-16 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20230404_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coffee_qty', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('grind_size', models.CharField(choices=[('Extra-Course', 'Extra-Course'), ('Coarse', 'Coarse'), ('Medium', 'Medium'), ('Medium-Fine', 'Medium-Fine'), ('Fine', 'Fine'), ('Superfine', 'Superfine')], default='Medium', max_length=20)),
                ('water_temp', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('water_volume', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('brew_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('method', models.TextField()),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
