# Generated by Django 3.2.18 on 2023-05-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name_plural': 'Recipes'},
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='brew_time',
            new_name='brew_time_mins',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='coffee_qty',
            new_name='coffee_qty_g',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='water_temp',
            new_name='water_temp_c',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='water_volume',
            new_name='water_volume_ml',
        ),
    ]
