# Generated by Django 3.2.18 on 2023-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230516_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipes',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
