# Generated by Django 3.2.18 on 2023-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230404_1033'),
        ('recipes', '0003_auto_20230516_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
